### ISSUE TITLE
test mode

### ISSUE THREAD

**Issue by ArtMin96** [tobelyan/omnipay-arca#2]
How can I switch to test mode?

**Comment by tobelyan** [comment]
$gateway->setTestMode(true);

The full initialization code will be like this

 $gateway = Omnipay::create('Arca');
        $gateway->setUserName($username);
        $gateway->setPassword($password);
        $gateway->setParameter('language',$lang);
        $gateway->setParameter('returnUrl',route('arca.check'));
        $gateway->setTestMode(true);
        $gateway->setParameter('jsonParams',json_encode(["FORCE_3DS2"=>"true"]));
        return $gateway;

**Comment by ArtMin96** [comment]
Thanks

**Comment by ArtMin96** [comment]
```php
public function initializeGateway()
{
    $gateway = Omnipay::create('Arca');
    $gateway->setUserName($this->getAccount());
    $gateway->setPassword($this->getSecret());
    $gateway->setParameter('language', $this->getLanguage());
    $gateway->setParameter('returnUrl', 'some route');
    $gateway->setTestMode($this->isTestMode());

    return $gateway;
}
```

and
```php
$gateway = $this->initializeGateway();

$gateway->setParameter('amount', 100);
$gateway->setParameter('transactionId', 123456);
$gateway->setParameter('description', 'Description');

$purchase = $gateway->purchase()->send();
$purchaseData = $purchase->getData();
```

And every time the answer is Access denied. But when I write a URL (https://ipay.arca.am/payment/rest/register.do?userName=login_api&password=pass&amount=100&language=ru&orderNumber=123456&description=Description&returnUrl=some-url) in the browser, everything is fine. Am I missing something in the code?

_errorCode: 5, errorMessage: 'Access denied'_

**Comment by tobelyan** [comment]
Most probably you are passing wrong credentials, as arca requires correct
unique test credentials

**Comment by ArtMin96** [comment]
Nevermind) everything was fine. Thanks again
