### ISSUE TITLE
Refund example

### ISSUE THREAD

**Issue by ArtMin96** [tobelyan/omnipay-arca#3]
Can you show me an example of how I can make a refund?

Here's my code:

```php
$gateway = Omnipay::create('Arca');
$gateway->setUserName($this->getAccount());
$gateway->setPassword($this->getSecret());

$response = $gateway->refund([
    'transactionId' => $order->getTransactionId(),
    'amount' => 1
])->send();

if ($response->isSuccessful()) {
    //...
}
```

Error message: Access denied

**Comment by tobelyan** [comment]
Your example is correct, 
just change transactionId=>$order->getTransactionId() with 'orderId'=>$order->getTransactionId()

**Comment by ArtMin96** [comment]
Thanks for the quick reply. I did that but there was a problem.

**Omnipay\Common\Exception\InvalidRequestException**
The `transactionId` parameter is required

**Comment by tobelyan** [comment]
Let me check the code i forgot how it is done :D

**Comment by tobelyan** [comment]
In Refund we see 
    public function getData()
    {
        $this->validate('transactionId', 'amount');

        $data = parent::getData();

        $data['orderId'] = $this->getTransactionId();
        $data['amount'] = $this->getAmountInteger();

        return $data;
    }
    
    so it means transactionId is correct

**Comment by tobelyan** [comment]
In Documentation of Arca they say 
Для возврата средств оплаты заказа используется запрос refund. Данную операцию можно
осуществлять, если есть соответствующие права в системе.

it means bank should approve permission to do refund request

**Comment by ArtMin96** [comment]
Thank you very much for your time and help :blush: :thumbsup:
